In [1]:
import numpy as np

# Floating point precision can be set:
a=1.123456789
np.set_printoptions(precision=4)
np.array([a])

array([1.1235])

In [2]:
# Long arrays can be summarised:
np.set_printoptions(threshold=5)
np.arange(10)



array([0, 1, 2, ..., 7, 8, 9])

In [3]:
# Small results can be suppressed:
np.set_printoptions(threshold=10)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# A custom formatter can be used to display array elements as desired:
eps = np.finfo(float).eps
x = np.arange(4.)
print(x**2 - (x + eps)**2)

np.set_printoptions(suppress=True)
print(x**2 - (x + eps)**2)


[-4.9304e-32 -4.4409e-16  0.0000e+00  0.0000e+00]
[-0. -0.  0.  0.]


In [5]:
# To put back the default options, you can use:
np.set_printoptions(edgeitems=3, infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

In [6]:
# Also to temporarily override options, use printoptions as a context manager:
with np.printoptions(precision=2, suppress=True, threshold=5):
    print(np.linspace(0, 10, 10))

[ 0.    1.11  2.22 ...  7.78  8.89 10.  ]
